//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.03 at 10:15:57 AM IST 
//


package com.onlinetutorialspoint.soap.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onlinetutorialspoint.soap.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onlinetutorialspoint.soap.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemRequest }
     * 
     */
    public ItemRequest createItemRequest() {
        return new ItemRequest();
    }

    /**
     * Create an instance of {@link ItemResponse }
     * 
     */
    public ItemResponse createItemResponse() {
        return new ItemResponse();
    }

    /**
     * Create an instance of {@link GetSearchOptions }
     * 
     */
    public GetSearchOptions createGetSearchOptions() {
        return new GetSearchOptions();
    }

    /**
     * Create an instance of {@link GetSearchOptionsResponse }
     * 
     */
    public GetSearchOptionsResponse createGetSearchOptionsResponse() {
        return new GetSearchOptionsResponse();
    }

    /**
     * Create an instance of {@link GetSearchOptionsByGuid }
     * 
     */
    public GetSearchOptionsByGuid createGetSearchOptionsByGuid() {
        return new GetSearchOptionsByGuid();
    }

    /**
     * Create an instance of {@link GetSearchOptionsByGuidResponse }
     * 
     */
    public GetSearchOptionsByGuidResponse createGetSearchOptionsByGuidResponse() {
        return new GetSearchOptionsByGuidResponse();
    }

    /**
     * Create an instance of {@link ExecuteSearch }
     * 
     */
    public ExecuteSearch createExecuteSearch() {
        return new ExecuteSearch();
    }

    /**
     * Create an instance of {@link ExecuteSearchResponse }
     * 
     */
    public ExecuteSearchResponse createExecuteSearchResponse() {
        return new ExecuteSearchResponse();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearch }
     * 
     */
    public ExecuteStatisticSearch createExecuteStatisticSearch() {
        return new ExecuteStatisticSearch();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchResponse }
     * 
     */
    public ExecuteStatisticSearchResponse createExecuteStatisticSearchResponse() {
        return new ExecuteStatisticSearchResponse();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchByReport }
     * 
     */
    public ExecuteStatisticSearchByReport createExecuteStatisticSearchByReport() {
        return new ExecuteStatisticSearchByReport();
    }

    /**
     * Create an instance of {@link ExecuteStatisticSearchByReportResponse }
     * 
     */
    public ExecuteStatisticSearchByReportResponse createExecuteStatisticSearchByReportResponse() {
        return new ExecuteStatisticSearchByReportResponse();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithSolutionId }
     * 
     */
    public ExecuteQuickSearchWithSolutionId createExecuteQuickSearchWithSolutionId() {
        return new ExecuteQuickSearchWithSolutionId();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithSolutionIdResponse }
     * 
     */
    public ExecuteQuickSearchWithSolutionIdResponse createExecuteQuickSearchWithSolutionIdResponse() {
        return new ExecuteQuickSearchWithSolutionIdResponse();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithModuleIds }
     * 
     */
    public ExecuteQuickSearchWithModuleIds createExecuteQuickSearchWithModuleIds() {
        return new ExecuteQuickSearchWithModuleIds();
    }

    /**
     * Create an instance of {@link ExecuteQuickSearchWithModuleIdsResponse }
     * 
     */
    public ExecuteQuickSearchWithModuleIdsResponse createExecuteQuickSearchWithModuleIdsResponse() {
        return new ExecuteQuickSearchWithModuleIdsResponse();
    }

    /**
     * Create an instance of {@link SearchRecords }
     * 
     */
    public SearchRecords createSearchRecords() {
        return new SearchRecords();
    }

    /**
     * Create an instance of {@link SearchRecordsResponse }
     * 
     */
    public SearchRecordsResponse createSearchRecordsResponse() {
        return new SearchRecordsResponse();
    }

    /**
     * Create an instance of {@link SearchRecordsByField }
     * 
     */
    public SearchRecordsByField createSearchRecordsByField() {
        return new SearchRecordsByField();
    }

    /**
     * Create an instance of {@link SearchRecordsByFieldResponse }
     * 
     */
    public SearchRecordsByFieldResponse createSearchRecordsByFieldResponse() {
        return new SearchRecordsByFieldResponse();
    }

    /**
     * Create an instance of {@link CheckSearchStatus }
     * 
     */
    public CheckSearchStatus createCheckSearchStatus() {
        return new CheckSearchStatus();
    }

    /**
     * Create an instance of {@link CheckSearchStatusResponse }
     * 
     */
    public CheckSearchStatusResponse createCheckSearchStatusResponse() {
        return new CheckSearchStatusResponse();
    }

    /**
     * Create an instance of {@link CheckSearchStatusByPageSize }
     * 
     */
    public CheckSearchStatusByPageSize createCheckSearchStatusByPageSize() {
        return new CheckSearchStatusByPageSize();
    }

    /**
     * Create an instance of {@link CheckSearchStatusByPageSizeResponse }
     * 
     */
    public CheckSearchStatusByPageSizeResponse createCheckSearchStatusByPageSizeResponse() {
        return new CheckSearchStatusByPageSizeResponse();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPage }
     * 
     */
    public RetrieveSearchResultsPage createRetrieveSearchResultsPage() {
        return new RetrieveSearchResultsPage();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageResponse }
     * 
     */
    public RetrieveSearchResultsPageResponse createRetrieveSearchResultsPageResponse() {
        return new RetrieveSearchResultsPageResponse();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageByPageSize }
     * 
     */
    public RetrieveSearchResultsPageByPageSize createRetrieveSearchResultsPageByPageSize() {
        return new RetrieveSearchResultsPageByPageSize();
    }

    /**
     * Create an instance of {@link RetrieveSearchResultsPageByPageSizeResponse }
     * 
     */
    public RetrieveSearchResultsPageByPageSizeResponse createRetrieveSearchResultsPageByPageSizeResponse() {
        return new RetrieveSearchResultsPageByPageSizeResponse();
    }

    /**
     * Create an instance of {@link GetReports }
     * 
     */
    public GetReports createGetReports() {
        return new GetReports();
    }

    /**
     * Create an instance of {@link GetReportsResponse }
     * 
     */
    public GetReportsResponse createGetReportsResponse() {
        return new GetReportsResponse();
    }

    /**
     * Create an instance of {@link SearchRecordsByReport }
     * 
     */
    public SearchRecordsByReport createSearchRecordsByReport() {
        return new SearchRecordsByReport();
    }

    /**
     * Create an instance of {@link SearchRecordsByReportResponse }
     * 
     */
    public SearchRecordsByReportResponse createSearchRecordsByReportResponse() {
        return new SearchRecordsByReportResponse();
    }

}
